-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sat_solver]: external functions.
-- This is a template file: hax seeded SatSolver/Assumptions/FunsExternal.lean
-- from it, and that copy is yours to fill in. This file is regenerated on
-- every extraction; diff it against your Assumptions file to see what the
-- extraction now requires.
import Aeneas
import CoreModels
import SatSolver.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open sat_solver

/-- [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Literal}::fmt]:
    Source: 'src/cnf.rs', lines 4:9-4:14
    Visibility: public -/
axiom cnf.Literal.Insts.CoreFmtDebug.fmt
  :
  cnf.Literal → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Clause}::fmt]:
    Source: 'src/cnf.rs', lines 10:9-10:14
    Visibility: public -/
axiom cnf.Clause.Insts.CoreFmtDebug.fmt
  :
  cnf.Clause → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Cnf}::fmt]:
    Source: 'src/cnf.rs', lines 13:9-13:14
    Visibility: public -/
axiom cnf.Cnf.Insts.CoreFmtDebug.fmt
  :
  cnf.Cnf → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Entry}::fmt]:
    Source: 'src/expr.rs', lines 11:9-11:14
    Visibility: public -/
axiom expr.Entry.Insts.CoreFmtDebug.fmt
  :
  expr.Entry → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Map}::fmt]:
    Source: 'src/expr.rs', lines 17:9-17:14
    Visibility: public -/
axiom expr.Map.Insts.CoreFmtDebug.fmt
  :
  expr.Map → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Expr}::fmt]:
    Source: 'src/expr.rs', lines 45:9-45:14
    Visibility: public -/
axiom expr.Expr.Insts.CoreFmtDebug.fmt
  :
  expr.Expr → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::expr::{impl core::fmt::Display for sat_solver::expr::Expr}::fmt]:
    Source: 'src/expr.rs', lines 56:4-65:5
    Visibility: public -/
axiom expr.Expr.Insts.CoreFmtDisplay.fmt
  :
  expr.Expr → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

