-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sat_solver]: function definitions
import Aeneas
import CoreModels
import SatSolver.Extraction.Types
import SatSolver.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sat_solver

/-- Trait implementation: [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Entry}]
    Source: 'src/expr.rs', lines 11:9-11:14 -/
@[reducible]
def expr.Entry.Insts.CoreFmtDebug : core.fmt.Debug expr.Entry := {
  fmt := expr.Entry.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Entry}::clone]:
    Source: 'src/expr.rs', lines 11:16-11:21
    Visibility: public -/
def expr.Entry.Insts.CoreCloneClone.clone
  (self : expr.Entry) : RustM expr.Entry := do
  let i ← core.U8.Insts.CoreCloneClone.clone self.key
  let b ← core.Bool.Insts.CoreCloneClone.clone self.value
  ok { key := i, value := b }

/-- Trait implementation: [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Entry}]
    Source: 'src/expr.rs', lines 11:16-11:21 -/
@[reducible]
impl_def expr.Entry.Insts.CoreCloneClone : core.clone.Clone expr.Entry := {
  clone := expr.Entry.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    expr.Entry.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::expr::{impl core::marker::StructuralPartialEq for sat_solver::expr::Entry}]
    Source: 'src/expr.rs', lines 11:23-11:32 -/
@[reducible]
def expr.Entry.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq expr.Entry := {
}

/-- [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Entry> for sat_solver::expr::Entry}::eq]:
    Source: 'src/expr.rs', lines 11:23-11:32
    Visibility: public -/
def expr.Entry.Insts.CoreCmpPartialEqEntry.eq
  (self : expr.Entry) (other : expr.Entry) : RustM Bool := do
  if self.key = other.key
  then ok (self.value = other.value)
  else ok false

/-- Trait implementation: [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Entry> for sat_solver::expr::Entry}]
    Source: 'src/expr.rs', lines 11:23-11:32 -/
@[reducible]
impl_def expr.Entry.Insts.CoreCmpPartialEqEntry : core.cmp.PartialEq expr.Entry
  expr.Entry := {
  eq := expr.Entry.Insts.CoreCmpPartialEqEntry.eq
  ne := core.cmp.PartialEq.ne.default expr.Entry.Insts.CoreCmpPartialEqEntry
}

/-- Trait implementation: [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 17:9-17:14 -/
@[reducible]
def expr.Map.Insts.CoreFmtDebug : core.fmt.Debug expr.Map := {
  fmt := expr.Map.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Map}::clone]:
    Source: 'src/expr.rs', lines 17:16-17:21
    Visibility: public -/
def expr.Map.Insts.CoreCloneClone.clone
  (self : expr.Map) : RustM expr.Map := do
  let v ←
    alloc.vec.Vec.Insts.CoreCloneClone.clone expr.Entry.Insts.CoreCloneClone
      self
  ok v

/-- Trait implementation: [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 17:16-17:21 -/
@[reducible]
impl_def expr.Map.Insts.CoreCloneClone : core.clone.Clone expr.Map := {
  clone := expr.Map.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    expr.Map.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::expr::{impl core::marker::StructuralPartialEq for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 17:23-17:32 -/
@[reducible]
def expr.Map.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq expr.Map := {
}

/-- [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Map> for sat_solver::expr::Map}::eq]:
    Source: 'src/expr.rs', lines 17:23-17:32
    Visibility: public -/
def expr.Map.Insts.CoreCmpPartialEqMap.eq
  (self : expr.Map) (other : expr.Map) : RustM Bool := do
  alloc.vec.Vec.Insts.CoreCmpPartialEqVec.eq
    expr.Entry.Insts.CoreCmpPartialEqEntry self other

/-- Trait implementation: [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Map> for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 17:23-17:32 -/
@[reducible]
impl_def expr.Map.Insts.CoreCmpPartialEqMap : core.cmp.PartialEq expr.Map
  expr.Map := {
  eq := expr.Map.Insts.CoreCmpPartialEqMap.eq
  ne := core.cmp.PartialEq.ne.default expr.Map.Insts.CoreCmpPartialEqMap
}

/-- [sat_solver::expr::{sat_solver::expr::Map}::new]:
    Source: 'src/expr.rs', lines 21:4-23:5
    Visibility: public -/
def expr.Map.new : RustM expr.Map := do
  let v ← alloc.vec.Vec.new expr.Entry
  ok v

/-- [sat_solver::expr::{sat_solver::expr::Map}::insert]: loop 0:
    Source: 'src/expr.rs', lines 26:8-33:5
    Visibility: public -/
@[rust_loop]
def expr.Map.insert_loop
  (deref_mut_back : Slice expr.Entry → alloc.vec.Vec expr.Entry)
  (iter_mut_back : core.slice.iter.IterMut expr.Entry → Slice expr.Entry)
  (iter : core.slice.iter.IterMut expr.Entry)
  (back : core.slice.iter.IterMut expr.Entry → core.slice.iter.IterMut
  expr.Entry) (key : Std.U8) (value : Bool) :
  RustM ((core.option.Option Bool) × (alloc.vec.Vec expr.Entry))
  := do
  let (o, iter1, next_back) ←
    core.slice.iter.IterMut.Insts.CoreIterTraitsIteratorIteratorMutAT.next iter
  match o with
  | core.option.Option.None =>
    let iter2 := next_back iter1 core.option.Option.None
    let s := iter_mut_back (back iter2)
    let v := deref_mut_back s
    let v1 ← alloc.vec.Vec.push v ({ key, value } : expr.Entry)
    ok (core.option.Option.None, v1)
  | core.option.Option.Some entry =>
    if entry.key = key
    then
      let (b, b1) ← core.mem.replace entry.value value
      let im :=
        next_back iter1 (core.option.Option.Some { entry with value := b1 })
      let s := iter_mut_back (back im)
      let v := deref_mut_back s
      ok (core.option.Option.Some b, v)
    else
      expr.Map.insert_loop deref_mut_back iter_mut_back iter1
        (fun im => let im1 := next_back im o
                   back im1) key value
partial_fixpoint

/-- [sat_solver::expr::{sat_solver::expr::Map}::insert]:
    Source: 'src/expr.rs', lines 25:4-33:5
    Visibility: public -/
def expr.Map.insert
  (self : expr.Map) (key : Std.U8) (value : Bool) :
  RustM ((core.option.Option Bool) × expr.Map)
  := do
  let (s, deref_mut_back) ←
    alloc.vec.Vec.Insts.CoreOpsDerefDerefMutSlice.deref_mut self
  let (iter, iter_mut_back) ← core.slice.Slice.iter_mut s
  let (o, v) ←
    expr.Map.insert_loop deref_mut_back iter_mut_back iter (fun im => im) key
      value
  ok (o, v)

/-- [sat_solver::expr::{sat_solver::expr::Map}::get]: loop 0:
    Source: 'src/expr.rs', lines 36:8-42:5
    Visibility: public -/
@[rust_loop]
def expr.Map.get_loop
  (iter : core.slice.iter.Iter expr.Entry) (key : Std.U8) :
  RustM (core.option.Option Bool)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok core.option.Option.None
  | core.option.Option.Some entry =>
    if entry.key = key
    then ok (core.option.Option.Some entry.value)
    else expr.Map.get_loop iter1 key
partial_fixpoint

/-- [sat_solver::expr::{sat_solver::expr::Map}::get]:
    Source: 'src/expr.rs', lines 35:4-42:5
    Visibility: public -/
def expr.Map.get
  (self : expr.Map) (key : Std.U8) : RustM (core.option.Option Bool) := do
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref self
  let iter ← core.slice.Slice.iter s
  expr.Map.get_loop iter key

/-- Trait implementation: [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 45:9-45:14 -/
@[reducible]
def expr.Expr.Insts.CoreFmtDebug : core.fmt.Debug expr.Expr := {
  fmt := expr.Expr.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Expr}::clone]:
    Source: 'src/expr.rs', lines 45:16-45:21
    Visibility: public -/
def expr.Expr.Insts.CoreCloneClone.clone
  (self : expr.Expr) : RustM expr.Expr := do
  match self with
  | expr.Expr.True => ok expr.Expr.True
  | expr.Expr.False => ok expr.Expr.False
  | expr.Expr.Variable __self_0 =>
    let i ← core.U8.Insts.CoreCloneClone.clone __self_0
    ok (expr.Expr.Variable i)
  | expr.Expr.Conj __self_0 __self_1 =>
    let e ← expr.Expr.Insts.CoreCloneClone.clone __self_0
    let e1 ← expr.Expr.Insts.CoreCloneClone.clone __self_1
    ok (expr.Expr.Conj e e1)
  | expr.Expr.Disj __self_0 __self_1 =>
    let e ← expr.Expr.Insts.CoreCloneClone.clone __self_0
    let e1 ← expr.Expr.Insts.CoreCloneClone.clone __self_1
    ok (expr.Expr.Disj e e1)
  | expr.Expr.Neg __self_0 =>
    let e ← expr.Expr.Insts.CoreCloneClone.clone __self_0
    ok (expr.Expr.Neg e)
partial_fixpoint

/-- Trait implementation: [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 45:16-45:21 -/
@[reducible]
impl_def expr.Expr.Insts.CoreCloneClone : core.clone.Clone expr.Expr := {
  clone := expr.Expr.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    expr.Expr.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::expr::{impl core::marker::StructuralPartialEq for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 45:23-45:32 -/
@[reducible]
def expr.Expr.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq expr.Expr := {
}

/-- [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Expr> for sat_solver::expr::Expr}::eq]:
    Source: 'src/expr.rs', lines 45:23-45:32
    Visibility: public -/
def expr.Expr.Insts.CoreCmpPartialEqExpr.eq
  (self : expr.Expr) (other : expr.Expr) : RustM Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | expr.Expr.True => ok true
    | expr.Expr.False => ok true
    | expr.Expr.Variable __self_0 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable __arg1_0 =>
        core.U8.Insts.CoreCmpPartialEqU8.eq __self_0 __arg1_0
      | expr.Expr.Conj _ _ => ok true
      | expr.Expr.Disj _ _ => ok true
      | expr.Expr.Neg _ => ok true
    | expr.Expr.Conj __self_0 __self_1 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable _ => ok true
      | expr.Expr.Conj __arg1_0 __arg1_1 =>
        let b ← expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_0 __arg1_0
        if b
        then expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_1 __arg1_1
        else ok false
      | expr.Expr.Disj _ _ => ok true
      | expr.Expr.Neg _ => ok true
    | expr.Expr.Disj __self_0 __self_1 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable _ => ok true
      | expr.Expr.Conj _ _ => ok true
      | expr.Expr.Disj __arg1_0 __arg1_1 =>
        let b ← expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_0 __arg1_0
        if b
        then expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_1 __arg1_1
        else ok false
      | expr.Expr.Neg _ => ok true
    | expr.Expr.Neg __self_0 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable _ => ok true
      | expr.Expr.Conj _ _ => ok true
      | expr.Expr.Disj _ _ => ok true
      | expr.Expr.Neg __arg1_0 =>
        expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_0 __arg1_0
  else ok false
partial_fixpoint

/-- Trait implementation: [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Expr> for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 45:23-45:32 -/
@[reducible]
impl_def expr.Expr.Insts.CoreCmpPartialEqExpr : core.cmp.PartialEq expr.Expr
  expr.Expr := {
  eq := expr.Expr.Insts.CoreCmpPartialEqExpr.eq
  ne := core.cmp.PartialEq.ne.default expr.Expr.Insts.CoreCmpPartialEqExpr
}

/-- Trait implementation: [sat_solver::expr::{impl core::fmt::Display for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 55:0-66:1 -/
@[reducible]
def expr.Expr.Insts.CoreFmtDisplay : core.fmt.Display expr.Expr := {
  fmt := expr.Expr.Insts.CoreFmtDisplay.fmt
}

/-- [sat_solver::expr::evaluate::{impl core::ops::function::FnOnce<(bool,), bool> for sat_solver::expr::evaluate::closure}::call_once]:
    Source: 'src/expr.rs', lines 139:51-139:57 -/
def expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
  (c : expr.evaluate.closure) (tupled_args : Bool) : RustM Bool := do
  ok (¬ tupled_args)

/-- Trait implementation: [sat_solver::expr::evaluate::{impl core::ops::function::FnOnce<(bool,), bool> for sat_solver::expr::evaluate::closure}]
    Source: 'src/expr.rs', lines 139:51-139:57 -/
@[reducible]
def expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool :
  core.ops.function.FnOnce expr.evaluate.closure Bool Bool := {
  call_once :=
    expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
}

/-- [sat_solver::expr::evaluate]:
    Source: 'src/expr.rs', lines 135:0-147:1
    Visibility: public -/
def expr.evaluate
  (expr1 : expr.Expr) (valuation : expr.Map) :
  RustM (core.result.Result Bool Unit)
  := do
  match expr1 with
  | expr.Expr.True => ok (core.result.Result.Ok true)
  | expr.Expr.False => ok (core.result.Result.Ok false)
  | expr.Expr.Variable s =>
    let o ← expr.Map.get valuation s
    match o with
    | core.option.Option.None => ok (core.result.Result.Err ())
    | core.option.Option.Some b => ok (core.result.Result.Ok b)
  | expr.Expr.Conj e1 e2 =>
    let r ← expr.evaluate e1 valuation
    let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val
      then
        let r1 ← expr.evaluate e2 valuation
        let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          ok (core.result.Result.Ok val1)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Bool (core.convert.From.Blanket Unit) residual
      else ok (core.result.Result.Ok false)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Bool (core.convert.From.Blanket Unit) residual
  | expr.Expr.Disj e1 e2 =>
    let r ← expr.evaluate e1 valuation
    let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val
      then ok (core.result.Result.Ok true)
      else
        let r1 ← expr.evaluate e2 valuation
        let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          ok (core.result.Result.Ok val1)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Bool (core.convert.From.Blanket Unit) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Bool (core.convert.From.Blanket Unit) residual
  | expr.Expr.Neg e =>
    let r ← expr.evaluate e valuation
    core.result.Result.map
      expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool r ()
partial_fixpoint

/-- [sat_solver::expr::contains_var]: loop 0:
    Source: 'src/expr.rs', lines 162:4-168:1 -/
@[rust_loop]
def expr.contains_var_loop
  (iter : core.slice.iter.Iter Std.U8) (v : Std.U8) : RustM Bool := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok false
  | core.option.Option.Some x =>
    if x = v
    then ok true
    else expr.contains_var_loop iter1 v
partial_fixpoint

/-- [sat_solver::expr::contains_var]:
    Source: 'src/expr.rs', lines 161:0-168:1 -/
def expr.contains_var (vars : Slice Std.U8) (v : Std.U8) : RustM Bool := do
  let iter ← core.slice.Slice.iter vars
  expr.contains_var_loop iter v

/-- [sat_solver::expr::merge_vars]: loop 0:
    Source: 'src/expr.rs', lines 171:4-175:5 -/
@[rust_loop]
def expr.merge_vars_loop
  (iter : core.slice.iter.Iter Std.U8) (dst : alloc.vec.Vec Std.U8) :
  RustM (alloc.vec.Vec Std.U8)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok dst
  | core.option.Option.Some v =>
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref dst
    let b ← expr.contains_var s v
    if b
    then expr.merge_vars_loop iter1 dst
    else let dst1 ← alloc.vec.Vec.push dst v
         expr.merge_vars_loop iter1 dst1
partial_fixpoint

/-- [sat_solver::expr::merge_vars]:
    Source: 'src/expr.rs', lines 170:0-176:1 -/
def expr.merge_vars
  (dst : alloc.vec.Vec Std.U8) (src : Slice Std.U8) :
  RustM (alloc.vec.Vec Std.U8)
  := do
  let iter ← core.slice.Slice.iter src
  expr.merge_vars_loop iter dst

/-- [sat_solver::expr::collect_vars_aux]:
    Source: 'src/expr.rs', lines 178:0-194:1 -/
def expr.collect_vars_aux
  (expr1 : expr.Expr) : RustM (alloc.vec.Vec Std.U8) := do
  match expr1 with
  | expr.Expr.True => alloc.vec.Vec.new Std.U8
  | expr.Expr.False => alloc.vec.Vec.new Std.U8
  | expr.Expr.Variable v =>
    let vars ← alloc.vec.Vec.new Std.U8
    alloc.vec.Vec.push vars v
  | expr.Expr.Conj e1 e2 =>
    let vs1 ← expr.collect_vars_aux e1
    let vs2 ← expr.collect_vars_aux e2
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vs2
    expr.merge_vars vs1 s
  | expr.Expr.Disj e1 e2 =>
    let vs1 ← expr.collect_vars_aux e1
    let vs2 ← expr.collect_vars_aux e2
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vs2
    expr.merge_vars vs1 s
  | expr.Expr.Neg e => expr.collect_vars_aux e
partial_fixpoint

/-- [sat_solver::expr::collect_vars]:
    Source: 'src/expr.rs', lines 196:0-198:1
    Visibility: public -/
def expr.collect_vars (expr1 : expr.Expr) : RustM (alloc.vec.Vec Std.U8) := do
  expr.collect_vars_aux expr1

/-- [sat_solver::sat_naive::initial_valuation]: loop 0:
    Source: 'src/sat_naive.rs', lines 8:4-10:5 -/
@[rust_loop]
def sat_naive.initial_valuation_loop
  (iter : core.slice.iter.Iter Std.U8) (map : expr.Map) : RustM expr.Map := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok map
  | core.option.Option.Some v =>
    let (_, map1) ← expr.Map.insert map v false
    sat_naive.initial_valuation_loop iter1 map1
partial_fixpoint

/-- [sat_solver::sat_naive::initial_valuation]:
    Source: 'src/sat_naive.rs', lines 5:0-13:1 -/
def sat_naive.initial_valuation (vars : Slice Std.U8) : RustM expr.Map := do
  let map ← expr.Map.new
  let iter ←
    core.SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
      vars
  sat_naive.initial_valuation_loop iter map

/-- [sat_solver::sat_naive::check_possible_valuations]:
    Source: 'src/sat_naive.rs', lines 15:0-34:1 -/
def sat_naive.check_possible_valuations
  (expr1 : expr.Expr) (vars : Slice Std.U8) (val : expr.Map) :
  RustM (Bool × expr.Map)
  := do
  let b ← core.slice.Slice.is_empty vars
  if b
  then
    let r ← expr.evaluate expr1 val
    let b1 ← core.result.Result.unwrap core.Tuple.Insts.CoreFmtDebug r
    ok (b1, val)
  else
    let v ← Slice.index_usize vars 0#usize
    let vs ←
      core.Slice.Insts.CoreOpsIndexIndex.index
        (core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8) vars { start := 1#usize }
    let (_, val1) ← expr.Map.insert val v false
    let (b1, val2) ← sat_naive.check_possible_valuations expr1 vs val1
    if b1
    then ok (true, val2)
    else
      let (_, val3) ← expr.Map.insert val2 v true
      let (b2, val4) ← sat_naive.check_possible_valuations expr1 vs val3
      if b2
      then ok (true, val4)
      else ok (false, val4)
partial_fixpoint

/-- [sat_solver::sat_naive::solve_sat]:
    Source: 'src/sat_naive.rs', lines 36:0-45:1
    Visibility: public -/
def sat_naive.solve_sat
  (expr1 : expr.Expr) : RustM (core.option.Option expr.Map) := do
  let vars ← expr.collect_vars expr1
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vars
  let val ← sat_naive.initial_valuation s
  let (b, val1) ← sat_naive.check_possible_valuations expr1 s val
  if b
  then ok (core.option.Option.Some val1)
  else ok core.option.Option.None

/-- [sat_solver::sat_naive_functional::naive_create_possible_valuations]: loop 0:
    Source: 'src/sat_naive_functional.rs', lines 19:4-27:5 -/
@[rust_loop]
def sat_naive_functional.naive_create_possible_valuations_loop
  (iter : core.slice.iter.Iter expr.Map) (v : Std.U8)
  (result : alloc.vec.Vec expr.Map) :
  RustM (alloc.vec.Vec expr.Map)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok result
  | core.option.Option.Some e =>
    let e_true ← expr.Map.Insts.CoreCloneClone.clone e
    let (_, e_true1) ← expr.Map.insert e_true v true
    let result1 ← alloc.vec.Vec.push result e_true1
    let (_, e_false) ← expr.Map.insert e_true v false
    let result2 ← alloc.vec.Vec.push result1 e_false
    sat_naive_functional.naive_create_possible_valuations_loop iter1 v result2
partial_fixpoint

/-- [sat_solver::sat_naive_functional::naive_create_possible_valuations]:
    Source: 'src/sat_naive_functional.rs', lines 5:0-30:1 -/
def sat_naive_functional.naive_create_possible_valuations
  (vars : Slice Std.U8) : RustM (alloc.vec.Vec expr.Map) := do
  let b ← core.slice.Slice.is_empty vars
  if b
  then
    let base ← alloc.vec.Vec.new expr.Map
    let m ← expr.Map.new
    alloc.vec.Vec.push base m
  else
    let v ← Slice.index_usize vars 0#usize
    let vs ←
      core.Slice.Insts.CoreOpsIndexIndex.index
        (core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U8) vars { start := 1#usize }
    let rest ← sat_naive_functional.naive_create_possible_valuations vs
    let result ← alloc.vec.Vec.new expr.Map
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref rest
    let iter ← core.slice.Slice.iter s
    sat_naive_functional.naive_create_possible_valuations_loop iter v result
partial_fixpoint

/-- [sat_solver::sat_naive_functional::solve_sat::{impl core::ops::function::FnOnce<(bool,), bool> for sat_solver::sat_naive_functional::solve_sat::closure}::call_once]:
    Source: 'src/sat_naive_functional.rs', lines 38:28-38:33 -/
def
  sat_naive_functional.solve_sat.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
  (c : sat_naive_functional.solve_sat.closure) (tupled_args : Bool) :
  RustM Bool
  := do
  ok tupled_args

/-- Trait implementation: [sat_solver::sat_naive_functional::solve_sat::{impl core::ops::function::FnOnce<(bool,), bool> for sat_solver::sat_naive_functional::solve_sat::closure}]
    Source: 'src/sat_naive_functional.rs', lines 38:28-38:33 -/
@[reducible]
def
  sat_naive_functional.solve_sat.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool
  : core.ops.function.FnOnce sat_naive_functional.solve_sat.closure Bool Bool
  := {
  call_once :=
    sat_naive_functional.solve_sat.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
}

/-- [sat_solver::sat_naive_functional::solve_sat]: loop 0:
    Source: 'src/sat_naive_functional.rs', lines 36:4-43:1
    Visibility: public -/
@[rust_loop]
def sat_naive_functional.solve_sat_loop
  (iter : alloc.vec.into_iter.IntoIter expr.Map) (expr1 : expr.Expr) :
  RustM (core.option.Option expr.Map)
  := do
  let (o, iter1) ←
    alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next iter
  match o with
  | core.option.Option.None => ok core.option.Option.None
  | core.option.Option.Some v =>
    let result ← expr.evaluate expr1 v
    let b ←
      core.result.Result.is_ok_and
        sat_naive_functional.solve_sat.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool
        result ()
    if b
    then ok o
    else sat_naive_functional.solve_sat_loop iter1 expr1
partial_fixpoint

/-- [sat_solver::sat_naive_functional::solve_sat]:
    Source: 'src/sat_naive_functional.rs', lines 32:0-43:1
    Visibility: public -/
def sat_naive_functional.solve_sat
  (expr1 : expr.Expr) : RustM (core.option.Option expr.Map) := do
  let vars ← expr.collect_vars expr1
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vars
  let valuations ← sat_naive_functional.naive_create_possible_valuations s
  let iter ←
    alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter
      valuations
  sat_naive_functional.solve_sat_loop iter expr1

end sat_solver
