-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sat_solver]: function definitions
import Aeneas
import CoreModels
import SatSolver.Extraction.Types
import SatSolver.Extraction.FunsExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace sat_solver

/-- Trait implementation: [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Literal}]
    Source: 'src/cnf.rs', lines 8:9-8:14 -/
@[reducible]
def cnf.Literal.Insts.CoreFmtDebug : core.fmt.Debug cnf.Literal := {
  fmt := cnf.Literal.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::cnf::{impl core::clone::Clone for sat_solver::cnf::Literal}::clone]:
    Source: 'src/cnf.rs', lines 8:16-8:21
    Visibility: public -/
def cnf.Literal.Insts.CoreCloneClone.clone
  (self : cnf.Literal) : RustM cnf.Literal := do
  let i ← core.U16.Insts.CoreCloneClone.clone self.var
  let b ← core.Bool.Insts.CoreCloneClone.clone self.negated
  ok { var := i, negated := b }

/-- Trait implementation: [sat_solver::cnf::{impl core::clone::Clone for sat_solver::cnf::Literal}]
    Source: 'src/cnf.rs', lines 8:16-8:21 -/
@[reducible]
impl_def cnf.Literal.Insts.CoreCloneClone : core.clone.Clone cnf.Literal := {
  clone := cnf.Literal.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    cnf.Literal.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::cnf::{impl core::marker::StructuralPartialEq for sat_solver::cnf::Literal}]
    Source: 'src/cnf.rs', lines 8:23-8:32 -/
@[reducible]
def cnf.Literal.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq cnf.Literal := {
}

/-- [sat_solver::cnf::{impl core::cmp::PartialEq<sat_solver::cnf::Literal> for sat_solver::cnf::Literal}::eq]:
    Source: 'src/cnf.rs', lines 8:23-8:32
    Visibility: public -/
def cnf.Literal.Insts.CoreCmpPartialEqLiteral.eq
  (self : cnf.Literal) (other : cnf.Literal) : RustM Bool := do
  if self.var = other.var
  then ok (self.negated = other.negated)
  else ok false

/-- Trait implementation: [sat_solver::cnf::{impl core::cmp::PartialEq<sat_solver::cnf::Literal> for sat_solver::cnf::Literal}]
    Source: 'src/cnf.rs', lines 8:23-8:32 -/
@[reducible]
impl_def cnf.Literal.Insts.CoreCmpPartialEqLiteral : core.cmp.PartialEq
  cnf.Literal cnf.Literal := {
  eq := cnf.Literal.Insts.CoreCmpPartialEqLiteral.eq
  ne := core.cmp.PartialEq.ne.default cnf.Literal.Insts.CoreCmpPartialEqLiteral
}

/-- Trait implementation: [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Clause}]
    Source: 'src/cnf.rs', lines 14:9-14:14 -/
@[reducible]
def cnf.Clause.Insts.CoreFmtDebug : core.fmt.Debug cnf.Clause := {
  fmt := cnf.Clause.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::cnf::{impl core::clone::Clone for sat_solver::cnf::Clause}::clone]:
    Source: 'src/cnf.rs', lines 14:16-14:21
    Visibility: public -/
def cnf.Clause.Insts.CoreCloneClone.clone
  (self : cnf.Clause) : RustM cnf.Clause := do
  let v ←
    alloc.vec.Vec.Insts.CoreCloneClone.clone cnf.Literal.Insts.CoreCloneClone
      self
  ok v

/-- Trait implementation: [sat_solver::cnf::{impl core::clone::Clone for sat_solver::cnf::Clause}]
    Source: 'src/cnf.rs', lines 14:16-14:21 -/
@[reducible]
impl_def cnf.Clause.Insts.CoreCloneClone : core.clone.Clone cnf.Clause := {
  clone := cnf.Clause.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    cnf.Clause.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::cnf::{impl core::marker::StructuralPartialEq for sat_solver::cnf::Clause}]
    Source: 'src/cnf.rs', lines 14:23-14:32 -/
@[reducible]
def cnf.Clause.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq cnf.Clause := {
}

/-- [sat_solver::cnf::{impl core::cmp::PartialEq<sat_solver::cnf::Clause> for sat_solver::cnf::Clause}::eq]:
    Source: 'src/cnf.rs', lines 14:23-14:32
    Visibility: public -/
def cnf.Clause.Insts.CoreCmpPartialEqClause.eq
  (self : cnf.Clause) (other : cnf.Clause) : RustM Bool := do
  alloc.vec.Vec.Insts.CoreCmpPartialEqVec.eq
    cnf.Literal.Insts.CoreCmpPartialEqLiteral self other

/-- Trait implementation: [sat_solver::cnf::{impl core::cmp::PartialEq<sat_solver::cnf::Clause> for sat_solver::cnf::Clause}]
    Source: 'src/cnf.rs', lines 14:23-14:32 -/
@[reducible]
impl_def cnf.Clause.Insts.CoreCmpPartialEqClause : core.cmp.PartialEq
  cnf.Clause cnf.Clause := {
  eq := cnf.Clause.Insts.CoreCmpPartialEqClause.eq
  ne := core.cmp.PartialEq.ne.default cnf.Clause.Insts.CoreCmpPartialEqClause
}

/-- Trait implementation: [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Cnf}]
    Source: 'src/cnf.rs', lines 17:9-17:14 -/
@[reducible]
def cnf.Cnf.Insts.CoreFmtDebug : core.fmt.Debug cnf.Cnf := {
  fmt := cnf.Cnf.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::cnf::{impl core::clone::Clone for sat_solver::cnf::Cnf}::clone]:
    Source: 'src/cnf.rs', lines 17:16-17:21
    Visibility: public -/
def cnf.Cnf.Insts.CoreCloneClone.clone (self : cnf.Cnf) : RustM cnf.Cnf := do
  let v ←
    alloc.vec.Vec.Insts.CoreCloneClone.clone cnf.Clause.Insts.CoreCloneClone
      self
  ok v

/-- Trait implementation: [sat_solver::cnf::{impl core::clone::Clone for sat_solver::cnf::Cnf}]
    Source: 'src/cnf.rs', lines 17:16-17:21 -/
@[reducible]
impl_def cnf.Cnf.Insts.CoreCloneClone : core.clone.Clone cnf.Cnf := {
  clone := cnf.Cnf.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    cnf.Cnf.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::cnf::{impl core::marker::StructuralPartialEq for sat_solver::cnf::Cnf}]
    Source: 'src/cnf.rs', lines 17:23-17:32 -/
@[reducible]
def cnf.Cnf.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq cnf.Cnf := {
}

/-- [sat_solver::cnf::{impl core::cmp::PartialEq<sat_solver::cnf::Cnf> for sat_solver::cnf::Cnf}::eq]:
    Source: 'src/cnf.rs', lines 17:23-17:32
    Visibility: public -/
def cnf.Cnf.Insts.CoreCmpPartialEqCnf.eq
  (self : cnf.Cnf) (other : cnf.Cnf) : RustM Bool := do
  alloc.vec.Vec.Insts.CoreCmpPartialEqVec.eq
    cnf.Clause.Insts.CoreCmpPartialEqClause self other

/-- Trait implementation: [sat_solver::cnf::{impl core::cmp::PartialEq<sat_solver::cnf::Cnf> for sat_solver::cnf::Cnf}]
    Source: 'src/cnf.rs', lines 17:23-17:32 -/
@[reducible]
impl_def cnf.Cnf.Insts.CoreCmpPartialEqCnf : core.cmp.PartialEq cnf.Cnf cnf.Cnf
  := {
  eq := cnf.Cnf.Insts.CoreCmpPartialEqCnf.eq
  ne := core.cmp.PartialEq.ne.default cnf.Cnf.Insts.CoreCmpPartialEqCnf
}

/-- [sat_solver::cnf::clause_union]: loop 0:
    Source: 'src/cnf.rs', lines 22:4-24:5 -/
@[rust_loop]
def cnf.clause_union_loop0
  (iter : core.slice.iter.Iter cnf.Literal) (lits : alloc.vec.Vec cnf.Literal)
  :
  RustM (alloc.vec.Vec cnf.Literal)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok lits
  | core.option.Option.Some l =>
    let l1 ← cnf.Literal.Insts.CoreCloneClone.clone l
    let lits1 ← alloc.vec.Vec.push lits l1
    cnf.clause_union_loop0 iter1 lits1
partial_fixpoint

/-- [sat_solver::cnf::clause_union]: loop 1:
    Source: 'src/cnf.rs', lines 25:4-27:5 -/
@[rust_loop]
def cnf.clause_union_loop1
  (iter : core.slice.iter.Iter cnf.Literal) (lits : alloc.vec.Vec cnf.Literal)
  :
  RustM (alloc.vec.Vec cnf.Literal)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok lits
  | core.option.Option.Some l =>
    let l1 ← cnf.Literal.Insts.CoreCloneClone.clone l
    let lits1 ← alloc.vec.Vec.push lits l1
    cnf.clause_union_loop1 iter1 lits1
partial_fixpoint

/-- [sat_solver::cnf::clause_union]:
    Source: 'src/cnf.rs', lines 20:0-29:1 -/
def cnf.clause_union
  (c1 : cnf.Clause) (c2 : cnf.Clause) : RustM cnf.Clause := do
  let lits ← alloc.vec.Vec.new cnf.Literal
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref c1
  let iter ← core.slice.Slice.iter s
  let lits1 ← cnf.clause_union_loop0 iter lits
  let s1 ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref c2
  let iter1 ← core.slice.Slice.iter s1
  let lits2 ← cnf.clause_union_loop1 iter1 lits1
  ok lits2

/-- [sat_solver::cnf::conj_cnf]: loop 0:
    Source: 'src/cnf.rs', lines 35:4-37:5 -/
@[rust_loop]
def cnf.conj_cnf_loop
  (iter : alloc.vec.into_iter.IntoIter cnf.Clause)
  (clauses : alloc.vec.Vec cnf.Clause) :
  RustM (alloc.vec.Vec cnf.Clause)
  := do
  let (o, iter1) ←
    alloc.vec.into_iter.IntoIter.Insts.CoreIterTraitsIteratorIterator.next iter
  match o with
  | core.option.Option.None => ok clauses
  | core.option.Option.Some c =>
    let clauses1 ← alloc.vec.Vec.push clauses c
    cnf.conj_cnf_loop iter1 clauses1
partial_fixpoint

/-- [sat_solver::cnf::conj_cnf]:
    Source: 'src/cnf.rs', lines 32:0-39:1 -/
def cnf.conj_cnf (c1 : cnf.Cnf) (c2 : cnf.Cnf) : RustM cnf.Cnf := do
  let iter ←
    alloc.vec.Vec.Insts.CoreIterTraitsCollectIntoIteratorTIntoIter.into_iter c2
  let clauses ← cnf.conj_cnf_loop iter c1
  ok clauses

/-- [sat_solver::cnf::distribute]: loop 1:
    Source: 'src/cnf.rs', lines 46:8-48:9 -/
@[rust_loop]
def cnf.distribute_loop0_loop0
  (iter : core.slice.iter.Iter cnf.Clause) (result : alloc.vec.Vec cnf.Clause)
  (clause1 : cnf.Clause) :
  RustM (alloc.vec.Vec cnf.Clause)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok result
  | core.option.Option.Some clause2 =>
    let c ← cnf.clause_union clause1 clause2
    let result1 ← alloc.vec.Vec.push result c
    cnf.distribute_loop0_loop0 iter1 result1 clause1
partial_fixpoint

/-- [sat_solver::cnf::distribute]: loop 0:
    Source: 'src/cnf.rs', lines 45:4-49:5 -/
@[rust_loop]
def cnf.distribute_loop0
  (iter : core.slice.iter.Iter cnf.Clause) (c2 : cnf.Cnf)
  (result : alloc.vec.Vec cnf.Clause) :
  RustM (alloc.vec.Vec cnf.Clause)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok result
  | core.option.Option.Some clause1 =>
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref c2
    let iter2 ← core.slice.Slice.iter s
    let result1 ← cnf.distribute_loop0_loop0 iter2 result clause1
    cnf.distribute_loop0 iter1 c2 result1
partial_fixpoint

/-- [sat_solver::cnf::distribute]:
    Source: 'src/cnf.rs', lines 43:0-51:1 -/
def cnf.distribute (c1 : cnf.Cnf) (c2 : cnf.Cnf) : RustM cnf.Cnf := do
  let result ← alloc.vec.Vec.new cnf.Clause
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref c1
  let iter ← core.slice.Slice.iter s
  let result1 ← cnf.distribute_loop0 iter c2 result
  ok result1

/-- [sat_solver::cnf::cnf_rec]:
    Source: 'src/cnf.rs', lines 58:0-94:1 -/
def cnf.cnf_rec (expr1 : expr.Expr) (negate : Bool) : RustM cnf.Cnf := do
  match expr1 with
  | expr.Expr.True =>
    if negate
    then
      let v ← alloc.vec.Vec.new cnf.Literal
      let y ←
        lift (Std.Array.to_slice (Array.make 1#usize [ v ] : Array cnf.Clause
          1#usize))
      let ret ← alloc.slice.Slice.into_vec y
      ok ret
    else let v ← alloc.vec.Vec.new cnf.Clause
         ok v
  | expr.Expr.False =>
    if negate
    then let v ← alloc.vec.Vec.new cnf.Clause
         ok v
    else
      let v ← alloc.vec.Vec.new cnf.Literal
      let y ←
        lift (Std.Array.to_slice (Array.make 1#usize [ v ] : Array cnf.Clause
          1#usize))
      let ret ← alloc.slice.Slice.into_vec y
      ok ret
  | expr.Expr.Variable v =>
    let y ←
      lift (Std.Array.to_slice
        (Array.make 1#usize [ { var := v, negated := negate } ] : Array
        cnf.Literal 1#usize))
    let ret ← alloc.slice.Slice.into_vec y
    let y1 ←
      lift (Std.Array.to_slice (Array.make 1#usize [ ret ] : Array cnf.Clause
        1#usize))
    let ret1 ← alloc.slice.Slice.into_vec y1
    ok ret1
  | expr.Expr.Conj e1 e2 =>
    if negate
    then
      let c ← cnf.cnf_rec e1 true
      let c1 ← cnf.cnf_rec e2 true
      cnf.distribute c c1
    else
      let c ← cnf.cnf_rec e1 false
      let c1 ← cnf.cnf_rec e2 false
      cnf.conj_cnf c c1
  | expr.Expr.Disj e1 e2 =>
    if negate
    then
      let c ← cnf.cnf_rec e1 true
      let c1 ← cnf.cnf_rec e2 true
      cnf.conj_cnf c c1
    else
      let c ← cnf.cnf_rec e1 false
      let c1 ← cnf.cnf_rec e2 false
      cnf.distribute c c1
  | expr.Expr.Neg e => cnf.cnf_rec e (¬ negate)
partial_fixpoint

/-- [sat_solver::cnf::to_cnf]:
    Source: 'src/cnf.rs', lines 96:0-98:1
    Visibility: public -/
def cnf.to_cnf (expr1 : expr.Expr) : RustM cnf.Cnf := do
  cnf.cnf_rec expr1 false

/-- [sat_solver::expr::{sat_solver::expr::Map}::get]:
    Source: 'src/expr.rs', lines 42:4-49:5
    Visibility: public -/
def expr.Map.get
  (self : expr.Map) (key : Std.U16) : RustM (core.option.Option Bool) := do
  let i ← lift (UScalar.cast .Usize key)
  let i1 ← alloc.vec.Vec.len self
  if i < i1
  then
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT (core.option.Option
      Bool)) self i
  else ok core.option.Option.None

/-- [sat_solver::cnf::eval_literal]:
    Source: 'src/cnf.rs', lines 103:0-108:1 -/
def cnf.eval_literal
  (lit : cnf.Literal) (valuation : expr.Map) :
  RustM (core.result.Result Bool Unit)
  := do
  let o ← expr.Map.get valuation lit.var
  match o with
  | core.option.Option.None => ok (core.result.Result.Err ())
  | core.option.Option.Some b =>
    if lit.negated
    then ok (core.result.Result.Ok (¬ b))
    else ok (core.result.Result.Ok b)

/-- [sat_solver::cnf::eval_clause]: loop 0:
    Source: 'src/cnf.rs', lines 111:4-117:1 -/
@[rust_loop]
def cnf.eval_clause_loop
  (iter : core.slice.iter.Iter cnf.Literal) (valuation : expr.Map) :
  RustM (core.result.Result Bool Unit)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok (core.result.Result.Ok false)
  | core.option.Option.Some lit =>
    let r ← cnf.eval_literal lit valuation
    let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val
      then ok (core.result.Result.Ok true)
      else cnf.eval_clause_loop iter1 valuation
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Bool (core.convert.From.Blanket Unit) residual
partial_fixpoint

/-- [sat_solver::cnf::eval_clause]:
    Source: 'src/cnf.rs', lines 110:0-117:1 -/
def cnf.eval_clause
  (clause : cnf.Clause) (valuation : expr.Map) :
  RustM (core.result.Result Bool Unit)
  := do
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref clause
  let iter ← core.slice.Slice.iter s
  cnf.eval_clause_loop iter valuation

/-- [sat_solver::cnf::eval_cnf]: loop 0:
    Source: 'src/cnf.rs', lines 120:4-126:1
    Visibility: public -/
@[rust_loop]
def cnf.eval_cnf_loop
  (iter : core.slice.iter.Iter cnf.Clause) (valuation : expr.Map) :
  RustM (core.result.Result Bool Unit)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok (core.result.Result.Ok true)
  | core.option.Option.Some clause =>
    let r ← cnf.eval_clause clause valuation
    let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val
      then cnf.eval_cnf_loop iter1 valuation
      else ok (core.result.Result.Ok false)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Bool (core.convert.From.Blanket Unit) residual
partial_fixpoint

/-- [sat_solver::cnf::eval_cnf]:
    Source: 'src/cnf.rs', lines 119:0-126:1
    Visibility: public -/
def cnf.eval_cnf
  (cnf1 : cnf.Cnf) (valuation : expr.Map) :
  RustM (core.result.Result Bool Unit)
  := do
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref cnf1
  let iter ← core.slice.Slice.iter s
  cnf.eval_cnf_loop iter valuation

/-- Trait implementation: [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 24:9-24:14 -/
@[reducible]
def expr.Map.Insts.CoreFmtDebug : core.fmt.Debug expr.Map := {
  fmt := expr.Map.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Map}::clone]:
    Source: 'src/expr.rs', lines 24:16-24:21
    Visibility: public -/
def expr.Map.Insts.CoreCloneClone.clone
  (self : expr.Map) : RustM expr.Map := do
  let v ←
    alloc.vec.Vec.Insts.CoreCloneClone.clone
      (core.option.Option.Insts.CoreCloneClone core.Bool.Insts.CoreCloneClone)
      self
  ok v

/-- Trait implementation: [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 24:16-24:21 -/
@[reducible]
impl_def expr.Map.Insts.CoreCloneClone : core.clone.Clone expr.Map := {
  clone := expr.Map.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    expr.Map.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::expr::{impl core::marker::StructuralPartialEq for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 24:23-24:32 -/
@[reducible]
def expr.Map.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq expr.Map := {
}

/-- [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Map> for sat_solver::expr::Map}::eq]:
    Source: 'src/expr.rs', lines 24:23-24:32
    Visibility: public -/
def expr.Map.Insts.CoreCmpPartialEqMap.eq
  (self : expr.Map) (other : expr.Map) : RustM Bool := do
  alloc.vec.Vec.Insts.CoreCmpPartialEqVec.eq
    (core.option.Option.Insts.CoreCmpPartialEqOption
    core.Bool.Insts.CoreCmpPartialEqBool) self other

/-- Trait implementation: [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Map> for sat_solver::expr::Map}]
    Source: 'src/expr.rs', lines 24:23-24:32 -/
@[reducible]
impl_def expr.Map.Insts.CoreCmpPartialEqMap : core.cmp.PartialEq expr.Map
  expr.Map := {
  eq := expr.Map.Insts.CoreCmpPartialEqMap.eq
  ne := core.cmp.PartialEq.ne.default expr.Map.Insts.CoreCmpPartialEqMap
}

/-- [sat_solver::expr::{sat_solver::expr::Map}::new]:
    Source: 'src/expr.rs', lines 28:4-30:5
    Visibility: public -/
def expr.Map.new : RustM expr.Map := do
  let v ← alloc.vec.Vec.new (core.option.Option Bool)
  ok v

/-- [sat_solver::expr::{sat_solver::expr::Map}::insert]: loop 0:
    Source: 'src/expr.rs', lines 34:8-36:9
    Visibility: public -/
@[rust_loop]
def expr.Map.insert_loop
  (self : expr.Map) (i : Std.Usize) :
  RustM (alloc.vec.Vec (core.option.Option Bool))
  := do
  let i1 ← alloc.vec.Vec.len self
  if i1 <= i
  then
    let v ← alloc.vec.Vec.push self core.option.Option.None
    expr.Map.insert_loop v i
  else ok self
partial_fixpoint

/-- [sat_solver::expr::{sat_solver::expr::Map}::insert]:
    Source: 'src/expr.rs', lines 32:4-40:5
    Visibility: public -/
def expr.Map.insert
  (self : expr.Map) (key : Std.U16) (value : Bool) :
  RustM ((core.option.Option Bool) × expr.Map)
  := do
  let i ← lift (UScalar.cast .Usize key)
  let v ← expr.Map.insert_loop self i
  let old ←
    alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
      (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT (core.option.Option
      Bool)) v i
  let (_, index_mut_back) ←
    alloc.vec.Vec.Insts.CoreOpsIndexIndexMut.index_mut
      (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT (core.option.Option
      Bool)) v i
  let v1 := index_mut_back (core.option.Option.Some value)
  ok (old, v1)

/-- Trait implementation: [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 52:9-52:14 -/
@[reducible]
def expr.Expr.Insts.CoreFmtDebug : core.fmt.Debug expr.Expr := {
  fmt := expr.Expr.Insts.CoreFmtDebug.fmt
}

/-- [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Expr}::clone]:
    Source: 'src/expr.rs', lines 52:16-52:21
    Visibility: public -/
def expr.Expr.Insts.CoreCloneClone.clone
  (self : expr.Expr) : RustM expr.Expr := do
  match self with
  | expr.Expr.True => ok expr.Expr.True
  | expr.Expr.False => ok expr.Expr.False
  | expr.Expr.Variable __self_0 =>
    let i ← core.U16.Insts.CoreCloneClone.clone __self_0
    ok (expr.Expr.Variable i)
  | expr.Expr.Conj __self_0 __self_1 =>
    let e ← expr.Expr.Insts.CoreCloneClone.clone __self_0
    let e1 ← expr.Expr.Insts.CoreCloneClone.clone __self_1
    ok (expr.Expr.Conj e e1)
  | expr.Expr.Disj __self_0 __self_1 =>
    let e ← expr.Expr.Insts.CoreCloneClone.clone __self_0
    let e1 ← expr.Expr.Insts.CoreCloneClone.clone __self_1
    ok (expr.Expr.Disj e e1)
  | expr.Expr.Neg __self_0 =>
    let e ← expr.Expr.Insts.CoreCloneClone.clone __self_0
    ok (expr.Expr.Neg e)
partial_fixpoint

/-- Trait implementation: [sat_solver::expr::{impl core::clone::Clone for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 52:16-52:21 -/
@[reducible]
impl_def expr.Expr.Insts.CoreCloneClone : core.clone.Clone expr.Expr := {
  clone := expr.Expr.Insts.CoreCloneClone.clone
  clone_from := core.clone.Clone.clone_from.default
    expr.Expr.Insts.CoreCloneClone
}

/-- Trait implementation: [sat_solver::expr::{impl core::marker::StructuralPartialEq for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 52:23-52:32 -/
@[reducible]
def expr.Expr.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq expr.Expr := {
}

/-- [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Expr> for sat_solver::expr::Expr}::eq]:
    Source: 'src/expr.rs', lines 52:23-52:32
    Visibility: public -/
def expr.Expr.Insts.CoreCmpPartialEqExpr.eq
  (self : expr.Expr) (other : expr.Expr) : RustM Bool := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  if self1 = other1
  then
    match self with
    | expr.Expr.True => ok true
    | expr.Expr.False => ok true
    | expr.Expr.Variable __self_0 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable __arg1_0 =>
        core.U16.Insts.CoreCmpPartialEqU16.eq __self_0 __arg1_0
      | expr.Expr.Conj _ _ => ok true
      | expr.Expr.Disj _ _ => ok true
      | expr.Expr.Neg _ => ok true
    | expr.Expr.Conj __self_0 __self_1 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable _ => ok true
      | expr.Expr.Conj __arg1_0 __arg1_1 =>
        let b ← expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_0 __arg1_0
        if b
        then expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_1 __arg1_1
        else ok false
      | expr.Expr.Disj _ _ => ok true
      | expr.Expr.Neg _ => ok true
    | expr.Expr.Disj __self_0 __self_1 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable _ => ok true
      | expr.Expr.Conj _ _ => ok true
      | expr.Expr.Disj __arg1_0 __arg1_1 =>
        let b ← expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_0 __arg1_0
        if b
        then expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_1 __arg1_1
        else ok false
      | expr.Expr.Neg _ => ok true
    | expr.Expr.Neg __self_0 =>
      match other with
      | expr.Expr.True => ok true
      | expr.Expr.False => ok true
      | expr.Expr.Variable _ => ok true
      | expr.Expr.Conj _ _ => ok true
      | expr.Expr.Disj _ _ => ok true
      | expr.Expr.Neg __arg1_0 =>
        expr.Expr.Insts.CoreCmpPartialEqExpr.eq __self_0 __arg1_0
  else ok false
partial_fixpoint

/-- Trait implementation: [sat_solver::expr::{impl core::cmp::PartialEq<sat_solver::expr::Expr> for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 52:23-52:32 -/
@[reducible]
impl_def expr.Expr.Insts.CoreCmpPartialEqExpr : core.cmp.PartialEq expr.Expr
  expr.Expr := {
  eq := expr.Expr.Insts.CoreCmpPartialEqExpr.eq
  ne := core.cmp.PartialEq.ne.default expr.Expr.Insts.CoreCmpPartialEqExpr
}

/-- Trait implementation: [sat_solver::expr::{impl core::fmt::Display for sat_solver::expr::Expr}]
    Source: 'src/expr.rs', lines 62:0-79:1 -/
@[reducible]
def expr.Expr.Insts.CoreFmtDisplay : core.fmt.Display expr.Expr := {
  fmt := expr.Expr.Insts.CoreFmtDisplay.fmt
}

/-- [sat_solver::expr::evaluate::{impl core::ops::function::FnOnce<(bool,), bool> for sat_solver::expr::evaluate::closure}::call_once]:
    Source: 'src/expr.rs', lines 152:51-152:57 -/
def expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
  (c : expr.evaluate.closure) (tupled_args : Bool) : RustM Bool := do
  ok (¬ tupled_args)

/-- Trait implementation: [sat_solver::expr::evaluate::{impl core::ops::function::FnOnce<(bool,), bool> for sat_solver::expr::evaluate::closure}]
    Source: 'src/expr.rs', lines 152:51-152:57 -/
@[reducible]
def expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool :
  core.ops.function.FnOnce expr.evaluate.closure Bool Bool := {
  call_once :=
    expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool.call_once
}

/-- [sat_solver::expr::evaluate]:
    Source: 'src/expr.rs', lines 148:0-160:1
    Visibility: public -/
def expr.evaluate
  (expr1 : expr.Expr) (valuation : expr.Map) :
  RustM (core.result.Result Bool Unit)
  := do
  match expr1 with
  | expr.Expr.True => ok (core.result.Result.Ok true)
  | expr.Expr.False => ok (core.result.Result.Ok false)
  | expr.Expr.Variable s =>
    let o ← expr.Map.get valuation s
    match o with
    | core.option.Option.None => ok (core.result.Result.Err ())
    | core.option.Option.Some b => ok (core.result.Result.Ok b)
  | expr.Expr.Conj e1 e2 =>
    let r ← expr.evaluate e1 valuation
    let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val
      then
        let r1 ← expr.evaluate e2 valuation
        let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          ok (core.result.Result.Ok val1)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Bool (core.convert.From.Blanket Unit) residual
      else ok (core.result.Result.Ok false)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Bool (core.convert.From.Blanket Unit) residual
  | expr.Expr.Disj e1 e2 =>
    let r ← expr.evaluate e1 valuation
    let cf ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r
    match cf with
    | core.ops.control_flow.ControlFlow.Continue val =>
      if val
      then ok (core.result.Result.Ok true)
      else
        let r1 ← expr.evaluate e2 valuation
        let cf1 ← core.result.Result.Insts.CoreOpsTry_traitTry.branch r1
        match cf1 with
        | core.ops.control_flow.ControlFlow.Continue val1 =>
          ok (core.result.Result.Ok val1)
        | core.ops.control_flow.ControlFlow.Break residual =>
          core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
            Bool (core.convert.From.Blanket Unit) residual
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTry_traitFromResidualResultInfallibleE.from_residual
        Bool (core.convert.From.Blanket Unit) residual
  | expr.Expr.Neg e =>
    let r ← expr.evaluate e valuation
    core.result.Result.map
      expr.evaluate.closure.Insts.CoreOpsFunctionFnOnceTupleBoolBool r ()
partial_fixpoint

/-- [sat_solver::expr::contains_var]: loop 0:
    Source: 'src/expr.rs', lines 182:4-188:1 -/
@[rust_loop]
def expr.contains_var_loop
  (iter : core.slice.iter.Iter Std.U16) (v : Std.U16) : RustM Bool := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok false
  | core.option.Option.Some x =>
    if x = v
    then ok true
    else expr.contains_var_loop iter1 v
partial_fixpoint

/-- [sat_solver::expr::contains_var]:
    Source: 'src/expr.rs', lines 181:0-188:1 -/
def expr.contains_var (vars : Slice Std.U16) (v : Std.U16) : RustM Bool := do
  let iter ← core.slice.Slice.iter vars
  expr.contains_var_loop iter v

/-- [sat_solver::expr::merge_vars]: loop 0:
    Source: 'src/expr.rs', lines 191:4-195:5 -/
@[rust_loop]
def expr.merge_vars_loop
  (iter : core.slice.iter.Iter Std.U16) (dst : alloc.vec.Vec Std.U16) :
  RustM (alloc.vec.Vec Std.U16)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok dst
  | core.option.Option.Some v =>
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref dst
    let b ← expr.contains_var s v
    if b
    then expr.merge_vars_loop iter1 dst
    else let dst1 ← alloc.vec.Vec.push dst v
         expr.merge_vars_loop iter1 dst1
partial_fixpoint

/-- [sat_solver::expr::merge_vars]:
    Source: 'src/expr.rs', lines 190:0-196:1 -/
def expr.merge_vars
  (dst : alloc.vec.Vec Std.U16) (src : Slice Std.U16) :
  RustM (alloc.vec.Vec Std.U16)
  := do
  let iter ← core.slice.Slice.iter src
  expr.merge_vars_loop iter dst

/-- [sat_solver::expr::collect_vars_aux]:
    Source: 'src/expr.rs', lines 198:0-214:1 -/
def expr.collect_vars_aux
  (expr1 : expr.Expr) : RustM (alloc.vec.Vec Std.U16) := do
  match expr1 with
  | expr.Expr.True => alloc.vec.Vec.new Std.U16
  | expr.Expr.False => alloc.vec.Vec.new Std.U16
  | expr.Expr.Variable v =>
    let vars ← alloc.vec.Vec.new Std.U16
    alloc.vec.Vec.push vars v
  | expr.Expr.Conj e1 e2 =>
    let vs1 ← expr.collect_vars_aux e1
    let vs2 ← expr.collect_vars_aux e2
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vs2
    expr.merge_vars vs1 s
  | expr.Expr.Disj e1 e2 =>
    let vs1 ← expr.collect_vars_aux e1
    let vs2 ← expr.collect_vars_aux e2
    let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vs2
    expr.merge_vars vs1 s
  | expr.Expr.Neg e => expr.collect_vars_aux e
partial_fixpoint

/-- [sat_solver::expr::collect_vars]:
    Source: 'src/expr.rs', lines 216:0-218:1
    Visibility: public -/
def expr.collect_vars (expr1 : expr.Expr) : RustM (alloc.vec.Vec Std.U16) := do
  expr.collect_vars_aux expr1

/-- [sat_solver::sat_dpll::is_satisfied]:
    Source: 'src/sat_dpll.rs', lines 11:0-13:1 -/
def sat_dpll.is_satisfied (cnf1 : cnf.Cnf) : RustM Bool := do
  alloc.vec.Vec.is_empty cnf1

/-- [sat_solver::sat_dpll::has_empty_clause]: loop 0:
    Source: 'src/sat_dpll.rs', lines 19:4-25:1 -/
@[rust_loop]
def sat_dpll.has_empty_clause_loop
  (iter : core.slice.iter.Iter cnf.Clause) : RustM Bool := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok false
  | core.option.Option.Some clause =>
    let b ← alloc.vec.Vec.is_empty clause
    if b
    then ok true
    else sat_dpll.has_empty_clause_loop iter1
partial_fixpoint

/-- [sat_solver::sat_dpll::has_empty_clause]:
    Source: 'src/sat_dpll.rs', lines 18:0-25:1 -/
def sat_dpll.has_empty_clause (cnf1 : cnf.Cnf) : RustM Bool := do
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref cnf1
  let iter ← core.slice.Slice.iter s
  sat_dpll.has_empty_clause_loop iter

/-- [sat_solver::sat_dpll::find_unit_literal]: loop 0:
    Source: 'src/sat_dpll.rs', lines 32:4-38:1 -/
@[rust_loop]
def sat_dpll.find_unit_literal_loop
  (iter : core.slice.iter.Iter cnf.Clause) :
  RustM (core.option.Option cnf.Literal)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok core.option.Option.None
  | core.option.Option.Some clause =>
    let i ← alloc.vec.Vec.len clause
    if i = 1#usize
    then
      let l ←
        alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
          (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT cnf.Literal) clause
          0#usize
      let l1 ← cnf.Literal.Insts.CoreCloneClone.clone l
      ok (core.option.Option.Some l1)
    else sat_dpll.find_unit_literal_loop iter1
partial_fixpoint

/-- [sat_solver::sat_dpll::find_unit_literal]:
    Source: 'src/sat_dpll.rs', lines 31:0-38:1 -/
def sat_dpll.find_unit_literal
  (cnf1 : cnf.Cnf) : RustM (core.option.Option cnf.Literal) := do
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref cnf1
  let iter ← core.slice.Slice.iter s
  sat_dpll.find_unit_literal_loop iter

/-- [sat_solver::sat_dpll::find_branch_var]: loop 0:
    Source: 'src/sat_dpll.rs', lines 46:4-52:1 -/
@[rust_loop]
def sat_dpll.find_branch_var_loop
  (iter : core.slice.iter.Iter cnf.Clause) :
  RustM (core.option.Option Std.U16)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok core.option.Option.None
  | core.option.Option.Some clause =>
    let b ← alloc.vec.Vec.is_empty clause
    if b
    then sat_dpll.find_branch_var_loop iter1
    else
      let l ←
        alloc.vec.Vec.Insts.CoreOpsIndexIndex.index
          (core.Usize.Insts.CoreSliceIndexSliceIndexSliceT cnf.Literal) clause
          0#usize
      ok (core.option.Option.Some l.var)
partial_fixpoint

/-- [sat_solver::sat_dpll::find_branch_var]:
    Source: 'src/sat_dpll.rs', lines 45:0-52:1 -/
def sat_dpll.find_branch_var
  (cnf1 : cnf.Cnf) : RustM (core.option.Option Std.U16) := do
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref cnf1
  let iter ← core.slice.Slice.iter s
  sat_dpll.find_branch_var_loop iter

/-- [sat_solver::sat_dpll::assign_clause]: loop 0:
    Source: 'src/sat_dpll.rs', lines 60:4-72:1 -/
@[rust_loop]
def sat_dpll.assign_clause_loop
  (iter : core.slice.iter.Iter cnf.Literal) (var : Std.U16) (value : Bool)
  (lits : alloc.vec.Vec cnf.Literal) :
  RustM (core.option.Option cnf.Clause)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok (core.option.Option.Some lits)
  | core.option.Option.Some lit =>
    if lit.var = var
    then
      if lit.negated != value
      then ok core.option.Option.None
      else sat_dpll.assign_clause_loop iter1 var value lits
    else
      let l ← cnf.Literal.Insts.CoreCloneClone.clone lit
      let lits1 ← alloc.vec.Vec.push lits l
      sat_dpll.assign_clause_loop iter1 var value lits1
partial_fixpoint

/-- [sat_solver::sat_dpll::assign_clause]:
    Source: 'src/sat_dpll.rs', lines 58:0-72:1 -/
def sat_dpll.assign_clause
  (clause : cnf.Clause) (var : Std.U16) (value : Bool) :
  RustM (core.option.Option cnf.Clause)
  := do
  let lits ← alloc.vec.Vec.new cnf.Literal
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref clause
  let iter ← core.slice.Slice.iter s
  sat_dpll.assign_clause_loop iter var value lits

/-- [sat_solver::sat_dpll::assign_cnf]: loop 0:
    Source: 'src/sat_dpll.rs', lines 80:4-84:5 -/
@[rust_loop]
def sat_dpll.assign_cnf_loop
  (iter : core.slice.iter.Iter cnf.Clause) (var : Std.U16) (value : Bool)
  (clauses : alloc.vec.Vec cnf.Clause) :
  RustM (alloc.vec.Vec cnf.Clause)
  := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok clauses
  | core.option.Option.Some clause =>
    let o1 ← sat_dpll.assign_clause clause var value
    match o1 with
    | core.option.Option.None =>
      sat_dpll.assign_cnf_loop iter1 var value clauses
    | core.option.Option.Some c =>
      let clauses1 ← alloc.vec.Vec.push clauses c
      sat_dpll.assign_cnf_loop iter1 var value clauses1
partial_fixpoint

/-- [sat_solver::sat_dpll::assign_cnf]:
    Source: 'src/sat_dpll.rs', lines 78:0-86:1 -/
def sat_dpll.assign_cnf
  (cnf1 : cnf.Cnf) (var : Std.U16) (value : Bool) : RustM cnf.Cnf := do
  let clauses ← alloc.vec.Vec.new cnf.Clause
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref cnf1
  let iter ← core.slice.Slice.iter s
  let clauses1 ← sat_dpll.assign_cnf_loop iter var value clauses
  ok clauses1

/-- [sat_solver::sat_dpll::dpll]:
    Source: 'src/sat_dpll.rs', lines 99:0-127:1 -/
def sat_dpll.dpll
  (cnf1 : cnf.Cnf) (val : expr.Map) : RustM (Bool × expr.Map) := do
  let b ← sat_dpll.is_satisfied cnf1
  if b
  then ok (true, val)
  else
    let b1 ← sat_dpll.has_empty_clause cnf1
    if b1
    then ok (false, val)
    else
      let o ← sat_dpll.find_unit_literal cnf1
      match o with
      | core.option.Option.None =>
        let o1 ← sat_dpll.find_branch_var cnf1
        match o1 with
        | core.option.Option.None => ok (false, val)
        | core.option.Option.Some v =>
          let (_, val1) ← expr.Map.insert val v true
          let c ← sat_dpll.assign_cnf cnf1 v true
          let (b2, val2) ← sat_dpll.dpll c val1
          if b2
          then ok (true, val2)
          else
            let (_, val3) ← expr.Map.insert val2 v false
            let c1 ← sat_dpll.assign_cnf cnf1 v false
            sat_dpll.dpll c1 val3
      | core.option.Option.Some lit =>
        let (_, val1) ← expr.Map.insert val lit.var (¬ lit.negated)
        let c ← sat_dpll.assign_cnf cnf1 lit.var (¬ lit.negated)
        sat_dpll.dpll c val1
partial_fixpoint

/-- [sat_solver::sat_naive::initial_valuation]: loop 0:
    Source: 'src/sat_naive.rs', lines 10:4-12:5
    Visibility: public -/
@[rust_loop]
def sat_naive.initial_valuation_loop
  (iter : core.slice.iter.Iter Std.U16) (map : expr.Map) : RustM expr.Map := do
  let (o, iter1) ←
    core.slice.iter.Iter.Insts.CoreIterTraitsIteratorIteratorSharedAT.next iter
  match o with
  | core.option.Option.None => ok map
  | core.option.Option.Some v =>
    let (_, map1) ← expr.Map.insert map v false
    sat_naive.initial_valuation_loop iter1 map1
partial_fixpoint

/-- [sat_solver::sat_naive::initial_valuation]:
    Source: 'src/sat_naive.rs', lines 7:0-15:1
    Visibility: public -/
def sat_naive.initial_valuation (vars : Slice Std.U16) : RustM expr.Map := do
  let map ← expr.Map.new
  let iter ←
    core.SharedASlice.Insts.CoreIterTraitsCollectIntoIteratorSharedATIter.into_iter
      vars
  sat_naive.initial_valuation_loop iter map

/-- [sat_solver::sat_dpll::solve_sat]:
    Source: 'src/sat_dpll.rs', lines 129:0-142:1
    Visibility: public -/
def sat_dpll.solve_sat
  (expr1 : expr.Expr) : RustM (core.option.Option expr.Map) := do
  let vars ← expr.collect_vars expr1
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vars
  let val ← sat_naive.initial_valuation s
  let cnf1 ← cnf.to_cnf expr1
  let (b, val1) ← sat_dpll.dpll cnf1 val
  if b
  then ok (core.option.Option.Some val1)
  else ok core.option.Option.None

/-- [sat_solver::sat_naive::check_possible_valuations]:
    Source: 'src/sat_naive.rs', lines 17:0-36:1 -/
def sat_naive.check_possible_valuations
  (expr1 : expr.Expr) (vars : Slice Std.U16) (val : expr.Map) :
  RustM (Bool × expr.Map)
  := do
  let b ← core.slice.Slice.is_empty vars
  if b
  then
    let r ← expr.evaluate expr1 val
    let b1 ← core.result.Result.unwrap core.Tuple.Insts.CoreFmtDebug r
    ok (b1, val)
  else
    let v ← Slice.index_usize vars 0#usize
    let vs ←
      core.Slice.Insts.CoreOpsIndexIndex.index
        (core.ops.range.RangeFromUsize.Insts.CoreSliceIndexSliceIndexSliceSlice
        Std.U16) vars { start := 1#usize }
    let (_, val1) ← expr.Map.insert val v false
    let (b1, val2) ← sat_naive.check_possible_valuations expr1 vs val1
    if b1
    then ok (true, val2)
    else
      let (_, val3) ← expr.Map.insert val2 v true
      let (b2, val4) ← sat_naive.check_possible_valuations expr1 vs val3
      if b2
      then ok (true, val4)
      else ok (false, val4)
partial_fixpoint

/-- [sat_solver::sat_naive::solve_sat]:
    Source: 'src/sat_naive.rs', lines 38:0-47:1
    Visibility: public -/
def sat_naive.solve_sat
  (expr1 : expr.Expr) : RustM (core.option.Option expr.Map) := do
  let vars ← expr.collect_vars expr1
  let s ← alloc.vec.Vec.Insts.CoreOpsDerefDerefSlice.deref vars
  let val ← sat_naive.initial_valuation s
  let (b, val1) ← sat_naive.check_possible_valuations expr1 s val
  if b
  then ok (core.option.Option.Some val1)
  else ok core.option.Option.None

end sat_solver
