-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sat_solver]: external functions.
-- This is a template file: hax seeded SatSolver/Assumptions/FunsExternal.lean
-- from it, and that copy is yours to fill in. This file is regenerated on
-- every extraction; diff it against your Assumptions file to see what the
-- extraction now requires.
import Aeneas
import CoreModels
import SatSolver.Extraction.Types
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048
open sat_solver

/-- [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Literal}::fmt]:
    Source: 'src/cnf.rs', lines 12:9-12:14
    Visibility: public -/
axiom cnf.Literal.Insts.CoreFmtDebug.fmt
  :
  cnf.Literal → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Clause}::fmt]:
    Source: 'src/cnf.rs', lines 18:9-18:14
    Visibility: public -/
axiom cnf.Clause.Insts.CoreFmtDebug.fmt
  :
  cnf.Clause → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::cnf::{impl core::fmt::Debug for sat_solver::cnf::Cnf}::fmt]:
    Source: 'src/cnf.rs', lines 21:9-21:14
    Visibility: public -/
axiom cnf.Cnf.Insts.CoreFmtDebug.fmt
  :
  cnf.Cnf → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Map}::fmt]:
    Source: 'src/expr.rs', lines 24:9-24:14
    Visibility: public -/
axiom expr.Map.Insts.CoreFmtDebug.fmt
  :
  expr.Map → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::expr::{impl core::fmt::Debug for sat_solver::expr::Expr}::fmt]:
    Source: 'src/expr.rs', lines 52:9-52:14
    Visibility: public -/
axiom expr.Expr.Insts.CoreFmtDebug.fmt
  :
  expr.Expr → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::expr::{impl core::fmt::Display for sat_solver::expr::Expr}::fmt]:
    Source: 'src/expr.rs', lines 63:4-78:5
    Visibility: public -/
axiom expr.Expr.Insts.CoreFmtDisplay.fmt
  :
  expr.Expr → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::sat_dpll::{impl core::fmt::Debug for sat_solver::sat_dpll::Transform}::fmt]:
    Source: 'src/sat_dpll.rs', lines 137:9-137:14
    Visibility: public -/
axiom sat_dpll.Transform.Insts.CoreFmtDebug.fmt
  :
  sat_dpll.Transform → core.fmt.Formatter → RustM ((core.result.Result Unit
    core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

/-- [sat_solver::sat_result::{impl core::fmt::Debug for sat_solver::sat_result::SatResult<T>}::fmt]:
    Source: 'src/sat_result.rs', lines 18:9-18:14
    Visibility: public -/
axiom sat_result.SatResult.Insts.CoreFmtDebug.fmt
  {T : Type} (corefmtDebugInst : core.fmt.Debug T) :
  sat_result.SatResult T → core.fmt.Formatter → RustM ((core.result.Result
    Unit core.fmt.Error) × core.fmt.Formatter × (core.fmt.Formatter →
    core.fmt.Formatter))

