-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [sat_solver]: type definitions
import Aeneas
import CoreModels
import SatSolver.Extraction.TypesExternal
open CoreModels Aeneas
open Aeneas.Std hiding namespace core alloc
open RustM ControlFlow Error
open Std.Do
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace sat_solver

/-- [sat_solver::cnf::Literal]
    Source: 'src/cnf.rs', lines 9:0-12:1
    Visibility: public -/
structure cnf.Literal where
  var : Std.U16
  negated : Bool

/-- [sat_solver::cnf::Clause]
    Source: 'src/cnf.rs', lines 15:0-15:36
    Visibility: public -/
@[reducible]
def cnf.Clause := alloc.vec.Vec cnf.Literal

/-- [sat_solver::cnf::Cnf]
    Source: 'src/cnf.rs', lines 18:0-18:32
    Visibility: public -/
@[reducible]
def cnf.Cnf := alloc.vec.Vec cnf.Clause

/-- [sat_solver::expr::Expr]
    Source: 'src/expr.rs', lines 53:0-60:1
    Visibility: public -/
@[discriminant isize]
inductive expr.Expr where
| True : expr.Expr
| False : expr.Expr
| Variable : Std.U16 → expr.Expr
| Conj : expr.Expr → expr.Expr → expr.Expr
| Disj : expr.Expr → expr.Expr → expr.Expr
| Neg : expr.Expr → expr.Expr

/-- [sat_solver::expr::Map]
    Source: 'src/expr.rs', lines 25:0-25:34
    Visibility: public -/
@[reducible]
def expr.Map := alloc.vec.Vec (core.option.Option Bool)

/-- [sat_solver::expr::evaluate::closure]
    Source: 'src/expr.rs', lines 152:51-152:57 -/
@[reducible]
def expr.evaluate.closure := Unit

end sat_solver
