(* File automatically generated by Hacspec *)
From Coq Require Import ZArith.
Require Import List.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.
Require Import Ascii.
Require Import String.
Require Import Coq.Floats.Floats.
From RecordUpdate Require Import RecordSet.
Import RecordSetNotations.
From Core Require Import Core.

(* NotImplementedYet *)





Inductive t_State : Type :=
| State_Idle
| State_AcceptingExpr
| State_Ready : t_Expr -> _
| State_Done : t_Option ((t_BTreeMap ((ascii)) ((bool)) ((t_Global)))) -> _.













Inductive t_Command : Type :=
| Command_Begin
| Command_GotExpr : t_Expr -> _
| Command_Compute
| Command_End.









Definition process_command (state : t_State) (com : t_Command) : t_Option ((t_State)) :=
  match (state,com) with
  | (State_Idle,Command_Begin) =>
    Option_Some (State_AcceptingExpr)
  | (State_AcceptingExpr,Command_GotExpr (e)) =>
    Option_Some (State_Ready (e))
  | (State_Ready (e),Command_Compute) =>
    Option_Some (State_Done (naive_solve_sat (e)))
  | (_,Command_End) =>
    Option_Some (State_Idle)
  | (_,_) =>
    Option_None
  end.

Fixpoint process_commands (state : t_State) (coms : t_Slice t_Command) : t_ControlFlow ((t_Option ((t_State)))) ((t_Option ((t_Option ((t_State)))))) :=
  let _ := if
    impl__is_empty (coms)
  then
    let hoist13 := ControlFlow_Break (Option_Some (state)) in
    ControlFlow_Continue (never_to_any (hoist13))
  else
    ControlFlow_Continue (tt) in
  ControlFlow_Continue (let c := f_index (coms) ((0 : t_usize)) in
  let cs := f_index (coms) (RangeFrom ((1 : t_usize))) in
  let new_state := process_command (state) (f_clone (c)) in
  Option_Some (process_commands (new_state) (cs))).
